# CAN-IDs
ID_FAHRBEFEHL = 0x101
ID_HINDERNIS = 0x202

# Fahrbefehle (1 Byte)
FAHRBEFEHL_VOR 	= [0x01]
FAHRBEFEHL_RUECK   = [0x02]
FAHRBEFEHL_RECHTS  = [0x03]
FAHRBEFEHL_LINKS   = [0x04]

# Bitpositionen für Hindernisse
HINDERNIS_VORNE_BIT  = 0
HINDERNIS_HINTEN_BIT = 1
# Für Erweiterung z. B.:
# HINDERNIS_RECHTS_BIT = 2
# HINDERNIS_LINKS_BIT  = 3

# Bitmasken (z. B. für Vergleich)
HINDERNIS_VORNE    	= 1 << HINDERNIS_VORNE_BIT	# = 0x01
HINDERNIS_HINTEN   	= 1 << HINDERNIS_HINTEN_BIT   # = 0x02
HINDERNIS_VORNE_HINTEN = HINDERNIS_VORNE | HINDERNIS_HINTEN
HINDERNIS_NONE     	= 0x00
